language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install: 
    - pip install -r requirements.txt

script:
    - python tests/test_lookup_output.py
    - python tests/test_available_now_output.py
    - python tests/test_now.py

notifications:
    email: false
