language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install: 
    - pip install -r requirements.txt

script:
    - python tests/test_available_now.py
    - python tests/test_lookup.py
    - python tests/test_builder.py
    - python tests/test_search_dict.py

notifications:
    email: false
