language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"

before_install:
    - pip install pep8

install: 
    - pip install -r requirements.txt

script:
    - find . -name '*\*.py' -exec pep8 {} +
    # - python tests/test_lookup_output.py
    # - python tests/test_available_now_output.py
    #- python tests/test_now.py

notifications:
    email: false
